dist: trusty

language: scala

jdk:
  - oraclejdk11

notifications:
  email:
    - karl.sjostrand@exini.com

before_install:
  - git fetch --tags

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    # stage="test" if no stage is specified
    - name: compile
      script: sbt compile
    - name: formatting
      script: ./bin/scalafmt --test
    # run ci-release only if previous stages passed
    - stage: release
      script: sbt ci-release

script: "sbt clean coverage test"
after_success: "sbt coverageReport coveralls"

