dist: trusty

os: linux

language: scala

jdk:
  - oraclejdk11

notifications:
  email:
    - karl.sjostrand@exini.com

before_install:
  - git fetch --tags

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present))

jobs:
  include:
    - stage: test
    - name: linting
      script: sbt scalafmtCheckAll
    - name: "test with coverage"
      script: "sbt clean coverage test"
      after_success: "sbt coverageReport coveralls"
    - stage: release
      script: sbt ci-release

